force_cast: error
force_try: error
#force_unwrapping: error

opt_in_rules:
  #- force_unwrapping

disabled_rules:
  - file_length
  - function_body_length
  - identifier_name
  - line_length
  - shorthand_operator
  - type_body_length
  - type_name

reporter: "xcode"
included:
  - Demo
  - FinniversKit
excluded:
  - bundler
analyzer_rules:
  - unused_import
