//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

import UIKit

private class BundleHelper {
}

extension UIImage {
    convenience init(named imageAsset: ImageAsset) {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle(for: BundleHelper.self)
        #endif
        self.init(named: imageAsset.rawValue, in: bundle, compatibleWith: nil)! // swiftlint:disable:this force_unwrapping
    }

    @objc class func assetNamed(_ assetName: String) -> UIImage {
        #if SWIFT_PACKAGE
        let bundle = Bundle.module
        #else
        let bundle = Bundle(for: BundleHelper.self)
        #endif
        return UIImage(named: assetName, in: bundle, compatibleWith: nil)! // swiftlint:disable:this force_unwrapping
    }
}

//swiftlint:disable:next blanket_disable_command
//swiftlint:disable superfluous_disable_command
//swiftlint:disable:next blanket_disable_command
//swiftlint:disable type_body_length
enum ImageAsset: String {
    case airplane = "Airplane"
    case autovex = "Autovex"
    case boat = "Boat"
    case briefcase = "Briefcase"
    case cabin = "Cabin"
    case carFront = "CarFront"
    case carPart = "CarPart"
    case carRent = "CarRent"
    case cars = "Cars"
    case chair = "Chair"
    case guitarBat = "GuitarBat"
    case honk = "Honk"
    case house = "House"
    case iceSkater = "IceSkater"
    case mittAnbud = "MittAnbud"
    case money = "Money"
    case motorcycle = "Motorcycle"
    case nettbil = "Nettbil"
    case oikotie = "Oikotie"
    case paw = "Paw"
    case shirt = "Shirt"
    case smartPhone = "SmartPhone"
    case storeFront = "StoreFront"
    case stroller = "Stroller"
    case tools = "Tools"
    case torget = "Torget"
    case vase = "Vase"
    case adManagementTrashcan
    case adsenseDemo
    case arrowCounterClockwise
    case avatar
    case bapShippable
    case betaImageSearch
    case blinkRocketMini
    case carIllustration
    case carPromo
    case carsCircleIllustration
    case checkCircle
    case checkCircleFilled
    case christmasPromotion
    case contract
    case creditCard
    case cross
    case displayTypeGrid
    case displayTypeList
    case dissatisfiedFace
    case easterEgg
    case emppatori
    case emptyMoon
    case emptyStateSaveSearch
    case eyeHide
    case favoriteActive
    case favorites
    case favouriteAdded
    case filledMoon
    case filter
    case finnLogo
    case finnLogoSimple
    case gift
    case heartEmpty
    case hjerterom
    case hobbyIllustration
    case home
    case iconRealestateApartments
    case iconRealestateBedrooms
    case iconRealestateOwner
    case iconRealestatePrice
    case magnifyingGlass
    case messages
    case more
    case motorcarFront
    case notifications
    case npCompare
    case npDrive
    case npHouseWeather
    case npPublicTransport
    case npRecommended
    case npSafeNeighborhood
    case npSchool
    case npStopwatch
    case npStore
    case npWalk
    case nyhetsbrevFraFinn
    case pencilPaper
    case pin
    case playVideo
    case plus
    case primingFavoritesComments
    case primingFavoritesSearch
    case primingFavoritesSharing
    case profile
    case rated
    case ratings
    case remove
    case removeFilterTag
    case republish
    case savedSearches
    case search
    case service
    case sold
    case stakeholder
    case torgetHelthjem
    case transactionJourneyCar
    case uncheckCircle
    case view
    case virtualViewing
    case warranty
    case webview
    case wrench
    case ybrukt
    case yourads

    static var imageNames: [ImageAsset] {
        return [
            .airplane,
            .autovex,
            .boat,
            .briefcase,
            .cabin,
            .carFront,
            .carPart,
            .carRent,
            .cars,
            .chair,
            .guitarBat,
            .honk,
            .house,
            .iceSkater,
            .mittAnbud,
            .money,
            .motorcycle,
            .nettbil,
            .oikotie,
            .paw,
            .shirt,
            .smartPhone,
            .storeFront,
            .stroller,
            .tools,
            .torget,
            .vase,
            .adManagementTrashcan,
            .adsenseDemo,
            .arrowCounterClockwise,
            .avatar,
            .bapShippable,
            .betaImageSearch,
            .blinkRocketMini,
            .carIllustration,
            .carPromo,
            .carsCircleIllustration,
            .checkCircle,
            .checkCircleFilled,
            .christmasPromotion,
            .contract,
            .creditCard,
            .cross,
            .displayTypeGrid,
            .displayTypeList,
            .dissatisfiedFace,
            .easterEgg,
            .emppatori,
            .emptyMoon,
            .emptyStateSaveSearch,
            .eyeHide,
            .favoriteActive,
            .favorites,
            .favouriteAdded,
            .filledMoon,
            .filter,
            .finnLogo,
            .finnLogoSimple,
            .gift,
            .heartEmpty,
            .hjerterom,
            .hobbyIllustration,
            .home,
            .iconRealestateApartments,
            .iconRealestateBedrooms,
            .iconRealestateOwner,
            .iconRealestatePrice,
            .magnifyingGlass,
            .messages,
            .more,
            .motorcarFront,
            .notifications,
            .npCompare,
            .npDrive,
            .npHouseWeather,
            .npPublicTransport,
            .npRecommended,
            .npSafeNeighborhood,
            .npSchool,
            .npStopwatch,
            .npStore,
            .npWalk,
            .nyhetsbrevFraFinn,
            .pencilPaper,
            .pin,
            .playVideo,
            .plus,
            .primingFavoritesComments,
            .primingFavoritesSearch,
            .primingFavoritesSharing,
            .profile,
            .rated,
            .ratings,
            .remove,
            .removeFilterTag,
            .republish,
            .savedSearches,
            .search,
            .service,
            .sold,
            .stakeholder,
            .torgetHelthjem,
            .transactionJourneyCar,
            .uncheckCircle,
            .view,
            .virtualViewing,
            .warranty,
            .webview,
            .wrench,
            .ybrukt,
            .yourads,
    ]
  }
}
