//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

import UIKit

public extension UIImage {
    public convenience init(named imageAsset: FinniversImageAsset) {
        self.init(named: imageAsset.rawValue, in: FinniversKit.bundle, compatibleWith: nil)!
    }
}

public enum FinniversImageAsset: String {
    case arrowDown
    case arrowRight
    case arrowUp
    case attachment
    case blockUser
    case boat
    case calendar
    case camera
    case car
    case check
    case checkmarkBig
    case classifieds
    case distance
    case download
    case edit
    case editBig
    case error
    case favouriteAdd
    case favouriteAddImg
    case favouriteAdded
    case favouriteAddedImg
    case favourites
    case gallery
    case gridView
    case help
    case hide
    case home
    case important
    case info
    case jobs
    case listView
    case mapDirections
    case mapDrawarea
    case mapMyposition
    case mc
    case messages
    case minus
    case miscLike
    case miscLiked
    case miscMoney
    case mittanbud
    case more
    case moreImg
    case moteplassen
    case noImage
    case notifications
    case onlyNew
    case pin
    case plus
    case profile
    case rate
    case rated
    case ratings
    case realestate
    case remove
    case search
    case searchBig
    case send
    case settings
    case share
    case shopping
    case smalljobs
    case success
    case trashcan
    case travel
    case vehicles
    case verified
    case view
    case webview
    case yourads
}
