//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

#import "AssetImageNames.h"

NSString *const FinniversKitAssetArrowdownImageName = @"arrowDown";
NSString *const FinniversKitAssetArrowrightImageName = @"arrowRight";
NSString *const FinniversKitAssetArrowupImageName = @"arrowUp";
NSString *const FinniversKitAssetAttachmentImageName = @"attachment";
NSString *const FinniversKitAssetBlockuserImageName = @"blockUser";
NSString *const FinniversKitAssetBoatImageName = @"boat";
NSString *const FinniversKitAssetCalendarImageName = @"calendar";
NSString *const FinniversKitAssetCameraImageName = @"camera";
NSString *const FinniversKitAssetCarImageName = @"car";
NSString *const FinniversKitAssetCheckImageName = @"check";
NSString *const FinniversKitAssetCheckmarkbigImageName = @"checkmarkBig";
NSString *const FinniversKitAssetClassifiedsImageName = @"classifieds";
NSString *const FinniversKitAssetDistanceImageName = @"distance";
NSString *const FinniversKitAssetDownloadImageName = @"download";
NSString *const FinniversKitAssetEditImageName = @"edit";
NSString *const FinniversKitAssetEditbigImageName = @"editBig";
NSString *const FinniversKitAssetErrorImageName = @"error";
NSString *const FinniversKitAssetFavouriteaddImageName = @"favouriteAdd";
NSString *const FinniversKitAssetFavouriteaddimgImageName = @"favouriteAddImg";
NSString *const FinniversKitAssetFavouriteaddedImageName = @"favouriteAdded";
NSString *const FinniversKitAssetFavouriteaddedimgImageName = @"favouriteAddedImg";
NSString *const FinniversKitAssetFavouritesImageName = @"favourites";
NSString *const FinniversKitAssetGalleryImageName = @"gallery";
NSString *const FinniversKitAssetGridviewImageName = @"gridView";
NSString *const FinniversKitAssetHelpImageName = @"help";
NSString *const FinniversKitAssetHideImageName = @"hide";
NSString *const FinniversKitAssetHomeImageName = @"home";
NSString *const FinniversKitAssetImportantImageName = @"important";
NSString *const FinniversKitAssetInfoImageName = @"info";
NSString *const FinniversKitAssetJobsImageName = @"jobs";
NSString *const FinniversKitAssetListviewImageName = @"listView";
NSString *const FinniversKitAssetMapdirectionsImageName = @"mapDirections";
NSString *const FinniversKitAssetMapdrawareaImageName = @"mapDrawarea";
NSString *const FinniversKitAssetMapmypositionImageName = @"mapMyposition";
NSString *const FinniversKitAssetMcImageName = @"mc";
NSString *const FinniversKitAssetMessagesImageName = @"messages";
NSString *const FinniversKitAssetMinusImageName = @"minus";
NSString *const FinniversKitAssetMisclikeImageName = @"miscLike";
NSString *const FinniversKitAssetMisclikedImageName = @"miscLiked";
NSString *const FinniversKitAssetMiscmoneyImageName = @"miscMoney";
NSString *const FinniversKitAssetMittanbudImageName = @"mittanbud";
NSString *const FinniversKitAssetMoreImageName = @"more";
NSString *const FinniversKitAssetMoreimgImageName = @"moreImg";
NSString *const FinniversKitAssetMoteplassenImageName = @"moteplassen";
NSString *const FinniversKitAssetNoimageImageName = @"noImage";
NSString *const FinniversKitAssetNotificationsImageName = @"notifications";
NSString *const FinniversKitAssetOnlynewImageName = @"onlyNew";
NSString *const FinniversKitAssetPinImageName = @"pin";
NSString *const FinniversKitAssetPlusImageName = @"plus";
NSString *const FinniversKitAssetProfileImageName = @"profile";
NSString *const FinniversKitAssetRateImageName = @"rate";
NSString *const FinniversKitAssetRatedImageName = @"rated";
NSString *const FinniversKitAssetRatingsImageName = @"ratings";
NSString *const FinniversKitAssetRealestateImageName = @"realestate";
NSString *const FinniversKitAssetRemoveImageName = @"remove";
NSString *const FinniversKitAssetSearchImageName = @"search";
NSString *const FinniversKitAssetSearchbigImageName = @"searchBig";
NSString *const FinniversKitAssetSendImageName = @"send";
NSString *const FinniversKitAssetSettingsImageName = @"settings";
NSString *const FinniversKitAssetShareImageName = @"share";
NSString *const FinniversKitAssetShoppingImageName = @"shopping";
NSString *const FinniversKitAssetSmalljobsImageName = @"smalljobs";
NSString *const FinniversKitAssetSuccessImageName = @"success";
NSString *const FinniversKitAssetTrashcanImageName = @"trashcan";
NSString *const FinniversKitAssetTravelImageName = @"travel";
NSString *const FinniversKitAssetVehiclesImageName = @"vehicles";
NSString *const FinniversKitAssetVerifiedImageName = @"verified";
NSString *const FinniversKitAssetViewImageName = @"view";
NSString *const FinniversKitAssetWebviewImageName = @"webview";
NSString *const FinniversKitAssetYouradsImageName = @"yourads";
