//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

#import "AssetImageNames.h"

NSString *const FinniversImageAssetarrowDownImageName = @"arrowDown";
NSString *const FinniversImageAssetarrowRightImageName = @"arrowRight";
NSString *const FinniversImageAssetarrowUpImageName = @"arrowUp";
NSString *const FinniversImageAssetattachmentImageName = @"attachment";
NSString *const FinniversImageAssetblockUserImageName = @"blockUser";
NSString *const FinniversImageAssetboatImageName = @"boat";
NSString *const FinniversImageAssetcalendarImageName = @"calendar";
NSString *const FinniversImageAssetcameraImageName = @"camera";
NSString *const FinniversImageAssetcarImageName = @"car";
NSString *const FinniversImageAssetcheckImageName = @"check";
NSString *const FinniversImageAssetcheckmarkBigImageName = @"checkmarkBig";
NSString *const FinniversImageAssetclassifiedsImageName = @"classifieds";
NSString *const FinniversImageAssetdistanceImageName = @"distance";
NSString *const FinniversImageAssetdownloadImageName = @"download";
NSString *const FinniversImageAsseteditImageName = @"edit";
NSString *const FinniversImageAsseteditBigImageName = @"editBig";
NSString *const FinniversImageAsseterrorImageName = @"error";
NSString *const FinniversImageAssetfavouriteAddImageName = @"favouriteAdd";
NSString *const FinniversImageAssetfavouriteAddImgImageName = @"favouriteAddImg";
NSString *const FinniversImageAssetfavouriteAddedImageName = @"favouriteAdded";
NSString *const FinniversImageAssetfavouriteAddedImgImageName = @"favouriteAddedImg";
NSString *const FinniversImageAssetfavouritesImageName = @"favourites";
NSString *const FinniversImageAssetgalleryImageName = @"gallery";
NSString *const FinniversImageAssetgridViewImageName = @"gridView";
NSString *const FinniversImageAssethelpImageName = @"help";
NSString *const FinniversImageAssethideImageName = @"hide";
NSString *const FinniversImageAssethomeImageName = @"home";
NSString *const FinniversImageAssetimportantImageName = @"important";
NSString *const FinniversImageAssetinfoImageName = @"info";
NSString *const FinniversImageAssetjobsImageName = @"jobs";
NSString *const FinniversImageAssetlistViewImageName = @"listView";
NSString *const FinniversImageAssetmapDirectionsImageName = @"mapDirections";
NSString *const FinniversImageAssetmapDrawareaImageName = @"mapDrawarea";
NSString *const FinniversImageAssetmapMypositionImageName = @"mapMyposition";
NSString *const FinniversImageAssetmcImageName = @"mc";
NSString *const FinniversImageAssetmessagesImageName = @"messages";
NSString *const FinniversImageAssetminusImageName = @"minus";
NSString *const FinniversImageAssetmiscLikeImageName = @"miscLike";
NSString *const FinniversImageAssetmiscLikedImageName = @"miscLiked";
NSString *const FinniversImageAssetmiscMoneyImageName = @"miscMoney";
NSString *const FinniversImageAssetmittanbudImageName = @"mittanbud";
NSString *const FinniversImageAssetmoreImageName = @"more";
NSString *const FinniversImageAssetmoreImgImageName = @"moreImg";
NSString *const FinniversImageAssetmoteplassenImageName = @"moteplassen";
NSString *const FinniversImageAssetnoImageImageName = @"noImage";
NSString *const FinniversImageAssetnotificationsImageName = @"notifications";
NSString *const FinniversImageAssetonlyNewImageName = @"onlyNew";
NSString *const FinniversImageAssetpinImageName = @"pin";
NSString *const FinniversImageAssetplusImageName = @"plus";
NSString *const FinniversImageAssetprofileImageName = @"profile";
NSString *const FinniversImageAssetrateImageName = @"rate";
NSString *const FinniversImageAssetratedImageName = @"rated";
NSString *const FinniversImageAssetratingsImageName = @"ratings";
NSString *const FinniversImageAssetrealestateImageName = @"realestate";
NSString *const FinniversImageAssetremoveImageName = @"remove";
NSString *const FinniversImageAssetsearchImageName = @"search";
NSString *const FinniversImageAssetsearchBigImageName = @"searchBig";
NSString *const FinniversImageAssetsendImageName = @"send";
NSString *const FinniversImageAssetsettingsImageName = @"settings";
NSString *const FinniversImageAssetshareImageName = @"share";
NSString *const FinniversImageAssetshoppingImageName = @"shopping";
NSString *const FinniversImageAssetsmalljobsImageName = @"smalljobs";
NSString *const FinniversImageAssetsuccessImageName = @"success";
NSString *const FinniversImageAssettrashcanImageName = @"trashcan";
NSString *const FinniversImageAssettravelImageName = @"travel";
NSString *const FinniversImageAssetvehiclesImageName = @"vehicles";
NSString *const FinniversImageAssetverifiedImageName = @"verified";
NSString *const FinniversImageAssetviewImageName = @"view";
NSString *const FinniversImageAssetwebviewImageName = @"webview";
NSString *const FinniversImageAssetyouradsImageName = @"yourads";
