//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

@import Foundation;

extern NSString *const FinniversKitAssetArrowdownImageName;
extern NSString *const FinniversKitAssetArrowrightImageName;
extern NSString *const FinniversKitAssetArrowupImageName;
extern NSString *const FinniversKitAssetAttachmentImageName;
extern NSString *const FinniversKitAssetBlockuserImageName;
extern NSString *const FinniversKitAssetBoatImageName;
extern NSString *const FinniversKitAssetCalendarImageName;
extern NSString *const FinniversKitAssetCameraImageName;
extern NSString *const FinniversKitAssetCarImageName;
extern NSString *const FinniversKitAssetCheckImageName;
extern NSString *const FinniversKitAssetCheckmarkbigImageName;
extern NSString *const FinniversKitAssetClassifiedsImageName;
extern NSString *const FinniversKitAssetDistanceImageName;
extern NSString *const FinniversKitAssetDownloadImageName;
extern NSString *const FinniversKitAssetEditImageName;
extern NSString *const FinniversKitAssetEditbigImageName;
extern NSString *const FinniversKitAssetErrorImageName;
extern NSString *const FinniversKitAssetFavouriteaddImageName;
extern NSString *const FinniversKitAssetFavouriteaddimgImageName;
extern NSString *const FinniversKitAssetFavouriteaddedImageName;
extern NSString *const FinniversKitAssetFavouriteaddedimgImageName;
extern NSString *const FinniversKitAssetFavouritesImageName;
extern NSString *const FinniversKitAssetGalleryImageName;
extern NSString *const FinniversKitAssetGridviewImageName;
extern NSString *const FinniversKitAssetHelpImageName;
extern NSString *const FinniversKitAssetHideImageName;
extern NSString *const FinniversKitAssetHomeImageName;
extern NSString *const FinniversKitAssetImportantImageName;
extern NSString *const FinniversKitAssetInfoImageName;
extern NSString *const FinniversKitAssetJobsImageName;
extern NSString *const FinniversKitAssetListviewImageName;
extern NSString *const FinniversKitAssetMapdirectionsImageName;
extern NSString *const FinniversKitAssetMapdrawareaImageName;
extern NSString *const FinniversKitAssetMapmypositionImageName;
extern NSString *const FinniversKitAssetMcImageName;
extern NSString *const FinniversKitAssetMessagesImageName;
extern NSString *const FinniversKitAssetMinusImageName;
extern NSString *const FinniversKitAssetMisclikeImageName;
extern NSString *const FinniversKitAssetMisclikedImageName;
extern NSString *const FinniversKitAssetMiscmoneyImageName;
extern NSString *const FinniversKitAssetMittanbudImageName;
extern NSString *const FinniversKitAssetMoreImageName;
extern NSString *const FinniversKitAssetMoreimgImageName;
extern NSString *const FinniversKitAssetMoteplassenImageName;
extern NSString *const FinniversKitAssetNoimageImageName;
extern NSString *const FinniversKitAssetNotificationsImageName;
extern NSString *const FinniversKitAssetOnlynewImageName;
extern NSString *const FinniversKitAssetPinImageName;
extern NSString *const FinniversKitAssetPlusImageName;
extern NSString *const FinniversKitAssetProfileImageName;
extern NSString *const FinniversKitAssetRateImageName;
extern NSString *const FinniversKitAssetRatedImageName;
extern NSString *const FinniversKitAssetRatingsImageName;
extern NSString *const FinniversKitAssetRealestateImageName;
extern NSString *const FinniversKitAssetRemoveImageName;
extern NSString *const FinniversKitAssetSearchImageName;
extern NSString *const FinniversKitAssetSearchbigImageName;
extern NSString *const FinniversKitAssetSendImageName;
extern NSString *const FinniversKitAssetSettingsImageName;
extern NSString *const FinniversKitAssetShareImageName;
extern NSString *const FinniversKitAssetShoppingImageName;
extern NSString *const FinniversKitAssetSmalljobsImageName;
extern NSString *const FinniversKitAssetSuccessImageName;
extern NSString *const FinniversKitAssetTrashcanImageName;
extern NSString *const FinniversKitAssetTravelImageName;
extern NSString *const FinniversKitAssetVehiclesImageName;
extern NSString *const FinniversKitAssetVerifiedImageName;
extern NSString *const FinniversKitAssetViewImageName;
extern NSString *const FinniversKitAssetWebviewImageName;
extern NSString *const FinniversKitAssetYouradsImageName;
