//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

@import Foundation;

extern NSString *const FinniversKitAssetarrowDownImageName;
extern NSString *const FinniversKitAssetarrowRightImageName;
extern NSString *const FinniversKitAssetarrowUpImageName;
extern NSString *const FinniversKitAssetattachmentImageName;
extern NSString *const FinniversKitAssetblockUserImageName;
extern NSString *const FinniversKitAssetboatImageName;
extern NSString *const FinniversKitAssetcalendarImageName;
extern NSString *const FinniversKitAssetcameraImageName;
extern NSString *const FinniversKitAssetcarImageName;
extern NSString *const FinniversKitAssetcheckImageName;
extern NSString *const FinniversKitAssetcheckmarkBigImageName;
extern NSString *const FinniversKitAssetclassifiedsImageName;
extern NSString *const FinniversKitAssetdistanceImageName;
extern NSString *const FinniversKitAssetdownloadImageName;
extern NSString *const FinniversKitAsseteditImageName;
extern NSString *const FinniversKitAsseteditBigImageName;
extern NSString *const FinniversKitAsseterrorImageName;
extern NSString *const FinniversKitAssetfavouriteAddImageName;
extern NSString *const FinniversKitAssetfavouriteAddImgImageName;
extern NSString *const FinniversKitAssetfavouriteAddedImageName;
extern NSString *const FinniversKitAssetfavouriteAddedImgImageName;
extern NSString *const FinniversKitAssetfavouritesImageName;
extern NSString *const FinniversKitAssetgalleryImageName;
extern NSString *const FinniversKitAssetgridViewImageName;
extern NSString *const FinniversKitAssethelpImageName;
extern NSString *const FinniversKitAssethideImageName;
extern NSString *const FinniversKitAssethomeImageName;
extern NSString *const FinniversKitAssetimportantImageName;
extern NSString *const FinniversKitAssetinfoImageName;
extern NSString *const FinniversKitAssetjobsImageName;
extern NSString *const FinniversKitAssetlistViewImageName;
extern NSString *const FinniversKitAssetmapDirectionsImageName;
extern NSString *const FinniversKitAssetmapDrawareaImageName;
extern NSString *const FinniversKitAssetmapMypositionImageName;
extern NSString *const FinniversKitAssetmcImageName;
extern NSString *const FinniversKitAssetmessagesImageName;
extern NSString *const FinniversKitAssetminusImageName;
extern NSString *const FinniversKitAssetmiscLikeImageName;
extern NSString *const FinniversKitAssetmiscLikedImageName;
extern NSString *const FinniversKitAssetmiscMoneyImageName;
extern NSString *const FinniversKitAssetmittanbudImageName;
extern NSString *const FinniversKitAssetmoreImageName;
extern NSString *const FinniversKitAssetmoreImgImageName;
extern NSString *const FinniversKitAssetmoteplassenImageName;
extern NSString *const FinniversKitAssetnoImageImageName;
extern NSString *const FinniversKitAssetnotificationsImageName;
extern NSString *const FinniversKitAssetonlyNewImageName;
extern NSString *const FinniversKitAssetpinImageName;
extern NSString *const FinniversKitAssetplusImageName;
extern NSString *const FinniversKitAssetprofileImageName;
extern NSString *const FinniversKitAssetrateImageName;
extern NSString *const FinniversKitAssetratedImageName;
extern NSString *const FinniversKitAssetratingsImageName;
extern NSString *const FinniversKitAssetrealestateImageName;
extern NSString *const FinniversKitAssetremoveImageName;
extern NSString *const FinniversKitAssetsearchImageName;
extern NSString *const FinniversKitAssetsearchBigImageName;
extern NSString *const FinniversKitAssetsendImageName;
extern NSString *const FinniversKitAssetsettingsImageName;
extern NSString *const FinniversKitAssetshareImageName;
extern NSString *const FinniversKitAssetshoppingImageName;
extern NSString *const FinniversKitAssetsmalljobsImageName;
extern NSString *const FinniversKitAssetsuccessImageName;
extern NSString *const FinniversKitAssettrashcanImageName;
extern NSString *const FinniversKitAssettravelImageName;
extern NSString *const FinniversKitAssetvehiclesImageName;
extern NSString *const FinniversKitAssetverifiedImageName;
extern NSString *const FinniversKitAssetviewImageName;
extern NSString *const FinniversKitAssetwebviewImageName;
extern NSString *const FinniversKitAssetyouradsImageName;
