//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

@import Foundation;

extern NSString *const FinniversImageAssetarrowDownImageName;
extern NSString *const FinniversImageAssetarrowRightImageName;
extern NSString *const FinniversImageAssetarrowUpImageName;
extern NSString *const FinniversImageAssetattachmentImageName;
extern NSString *const FinniversImageAssetblockUserImageName;
extern NSString *const FinniversImageAssetboatImageName;
extern NSString *const FinniversImageAssetcalendarImageName;
extern NSString *const FinniversImageAssetcameraImageName;
extern NSString *const FinniversImageAssetcarImageName;
extern NSString *const FinniversImageAssetcheckImageName;
extern NSString *const FinniversImageAssetcheckmarkBigImageName;
extern NSString *const FinniversImageAssetclassifiedsImageName;
extern NSString *const FinniversImageAssetdistanceImageName;
extern NSString *const FinniversImageAssetdownloadImageName;
extern NSString *const FinniversImageAsseteditImageName;
extern NSString *const FinniversImageAsseteditBigImageName;
extern NSString *const FinniversImageAsseterrorImageName;
extern NSString *const FinniversImageAssetfavouriteAddImageName;
extern NSString *const FinniversImageAssetfavouriteAddImgImageName;
extern NSString *const FinniversImageAssetfavouriteAddedImageName;
extern NSString *const FinniversImageAssetfavouriteAddedImgImageName;
extern NSString *const FinniversImageAssetfavouritesImageName;
extern NSString *const FinniversImageAssetgalleryImageName;
extern NSString *const FinniversImageAssetgridViewImageName;
extern NSString *const FinniversImageAssethelpImageName;
extern NSString *const FinniversImageAssethideImageName;
extern NSString *const FinniversImageAssethomeImageName;
extern NSString *const FinniversImageAssetimportantImageName;
extern NSString *const FinniversImageAssetinfoImageName;
extern NSString *const FinniversImageAssetjobsImageName;
extern NSString *const FinniversImageAssetlistViewImageName;
extern NSString *const FinniversImageAssetmapDirectionsImageName;
extern NSString *const FinniversImageAssetmapDrawareaImageName;
extern NSString *const FinniversImageAssetmapMypositionImageName;
extern NSString *const FinniversImageAssetmcImageName;
extern NSString *const FinniversImageAssetmessagesImageName;
extern NSString *const FinniversImageAssetminusImageName;
extern NSString *const FinniversImageAssetmiscLikeImageName;
extern NSString *const FinniversImageAssetmiscLikedImageName;
extern NSString *const FinniversImageAssetmiscMoneyImageName;
extern NSString *const FinniversImageAssetmittanbudImageName;
extern NSString *const FinniversImageAssetmoreImageName;
extern NSString *const FinniversImageAssetmoreImgImageName;
extern NSString *const FinniversImageAssetmoteplassenImageName;
extern NSString *const FinniversImageAssetnoImageImageName;
extern NSString *const FinniversImageAssetnotificationsImageName;
extern NSString *const FinniversImageAssetonlyNewImageName;
extern NSString *const FinniversImageAssetpinImageName;
extern NSString *const FinniversImageAssetplusImageName;
extern NSString *const FinniversImageAssetprofileImageName;
extern NSString *const FinniversImageAssetrateImageName;
extern NSString *const FinniversImageAssetratedImageName;
extern NSString *const FinniversImageAssetratingsImageName;
extern NSString *const FinniversImageAssetrealestateImageName;
extern NSString *const FinniversImageAssetremoveImageName;
extern NSString *const FinniversImageAssetsearchImageName;
extern NSString *const FinniversImageAssetsearchBigImageName;
extern NSString *const FinniversImageAssetsendImageName;
extern NSString *const FinniversImageAssetsettingsImageName;
extern NSString *const FinniversImageAssetshareImageName;
extern NSString *const FinniversImageAssetshoppingImageName;
extern NSString *const FinniversImageAssetsmalljobsImageName;
extern NSString *const FinniversImageAssetsuccessImageName;
extern NSString *const FinniversImageAssettrashcanImageName;
extern NSString *const FinniversImageAssettravelImageName;
extern NSString *const FinniversImageAssetvehiclesImageName;
extern NSString *const FinniversImageAssetverifiedImageName;
extern NSString *const FinniversImageAssetviewImageName;
extern NSString *const FinniversImageAssetwebviewImageName;
extern NSString *const FinniversImageAssetyouradsImageName;
