//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

#import "AssetImageNames.h"

NSString *const FinniversKitAssetarrowDownImageName = @"arrowDown";
NSString *const FinniversKitAssetarrowRightImageName = @"arrowRight";
NSString *const FinniversKitAssetarrowUpImageName = @"arrowUp";
NSString *const FinniversKitAssetattachmentImageName = @"attachment";
NSString *const FinniversKitAssetblockUserImageName = @"blockUser";
NSString *const FinniversKitAssetboatImageName = @"boat";
NSString *const FinniversKitAssetcalendarImageName = @"calendar";
NSString *const FinniversKitAssetcameraImageName = @"camera";
NSString *const FinniversKitAssetcarImageName = @"car";
NSString *const FinniversKitAssetcheckImageName = @"check";
NSString *const FinniversKitAssetcheckmarkBigImageName = @"checkmarkBig";
NSString *const FinniversKitAssetclassifiedsImageName = @"classifieds";
NSString *const FinniversKitAssetdistanceImageName = @"distance";
NSString *const FinniversKitAssetdownloadImageName = @"download";
NSString *const FinniversKitAsseteditImageName = @"edit";
NSString *const FinniversKitAsseteditBigImageName = @"editBig";
NSString *const FinniversKitAsseterrorImageName = @"error";
NSString *const FinniversKitAssetfavouriteAddImageName = @"favouriteAdd";
NSString *const FinniversKitAssetfavouriteAddImgImageName = @"favouriteAddImg";
NSString *const FinniversKitAssetfavouriteAddedImageName = @"favouriteAdded";
NSString *const FinniversKitAssetfavouriteAddedImgImageName = @"favouriteAddedImg";
NSString *const FinniversKitAssetfavouritesImageName = @"favourites";
NSString *const FinniversKitAssetgalleryImageName = @"gallery";
NSString *const FinniversKitAssetgridViewImageName = @"gridView";
NSString *const FinniversKitAssethelpImageName = @"help";
NSString *const FinniversKitAssethideImageName = @"hide";
NSString *const FinniversKitAssethomeImageName = @"home";
NSString *const FinniversKitAssetimportantImageName = @"important";
NSString *const FinniversKitAssetinfoImageName = @"info";
NSString *const FinniversKitAssetjobsImageName = @"jobs";
NSString *const FinniversKitAssetlistViewImageName = @"listView";
NSString *const FinniversKitAssetmapDirectionsImageName = @"mapDirections";
NSString *const FinniversKitAssetmapDrawareaImageName = @"mapDrawarea";
NSString *const FinniversKitAssetmapMypositionImageName = @"mapMyposition";
NSString *const FinniversKitAssetmcImageName = @"mc";
NSString *const FinniversKitAssetmessagesImageName = @"messages";
NSString *const FinniversKitAssetminusImageName = @"minus";
NSString *const FinniversKitAssetmiscLikeImageName = @"miscLike";
NSString *const FinniversKitAssetmiscLikedImageName = @"miscLiked";
NSString *const FinniversKitAssetmiscMoneyImageName = @"miscMoney";
NSString *const FinniversKitAssetmittanbudImageName = @"mittanbud";
NSString *const FinniversKitAssetmoreImageName = @"more";
NSString *const FinniversKitAssetmoreImgImageName = @"moreImg";
NSString *const FinniversKitAssetmoteplassenImageName = @"moteplassen";
NSString *const FinniversKitAssetnoImageImageName = @"noImage";
NSString *const FinniversKitAssetnotificationsImageName = @"notifications";
NSString *const FinniversKitAssetonlyNewImageName = @"onlyNew";
NSString *const FinniversKitAssetpinImageName = @"pin";
NSString *const FinniversKitAssetplusImageName = @"plus";
NSString *const FinniversKitAssetprofileImageName = @"profile";
NSString *const FinniversKitAssetrateImageName = @"rate";
NSString *const FinniversKitAssetratedImageName = @"rated";
NSString *const FinniversKitAssetratingsImageName = @"ratings";
NSString *const FinniversKitAssetrealestateImageName = @"realestate";
NSString *const FinniversKitAssetremoveImageName = @"remove";
NSString *const FinniversKitAssetsearchImageName = @"search";
NSString *const FinniversKitAssetsearchBigImageName = @"searchBig";
NSString *const FinniversKitAssetsendImageName = @"send";
NSString *const FinniversKitAssetsettingsImageName = @"settings";
NSString *const FinniversKitAssetshareImageName = @"share";
NSString *const FinniversKitAssetshoppingImageName = @"shopping";
NSString *const FinniversKitAssetsmalljobsImageName = @"smalljobs";
NSString *const FinniversKitAssetsuccessImageName = @"success";
NSString *const FinniversKitAssettrashcanImageName = @"trashcan";
NSString *const FinniversKitAssettravelImageName = @"travel";
NSString *const FinniversKitAssetvehiclesImageName = @"vehicles";
NSString *const FinniversKitAssetverifiedImageName = @"verified";
NSString *const FinniversKitAssetviewImageName = @"view";
NSString *const FinniversKitAssetwebviewImageName = @"webview";
NSString *const FinniversKitAssetyouradsImageName = @"yourads";
