//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

#import "FinniversImageAsset.h"

NSString *const FinniversImageAssetadManagementShare = @"adManagementShare";
NSString *const FinniversImageAssetadManagementTrashcan = @"adManagementTrashcan";
NSString *const FinniversImageAssetarrowDown = @"arrowDown";
NSString *const FinniversImageAssetarrowRight = @"arrowRight";
NSString *const FinniversImageAssetarrowUp = @"arrowUp";
NSString *const FinniversImageAssetattachment = @"attachment";
NSString *const FinniversImageAssetballoon0 = @"balloon0";
NSString *const FinniversImageAssetballoon1 = @"balloon1";
NSString *const FinniversImageAssetballoon2 = @"balloon2";
NSString *const FinniversImageAssetballoon9 = @"balloon9";
NSString *const FinniversImageAssetblockUser = @"blockUser";
NSString *const FinniversImageAssetboat = @"boat";
NSString *const FinniversImageAssetcalendar = @"calendar";
NSString *const FinniversImageAssetcamera = @"camera";
NSString *const FinniversImageAssetcandyCane = @"candyCane";
NSString *const FinniversImageAssetcar = @"car";
NSString *const FinniversImageAssetcheck = @"check";
NSString *const FinniversImageAssetcheckCircle = @"checkCircle";
NSString *const FinniversImageAssetcheckmarkBig = @"checkmarkBig";
NSString *const FinniversImageAssetclassifieds = @"classifieds";
NSString *const FinniversImageAssetclose = @"close";
NSString *const FinniversImageAssetdistance = @"distance";
NSString *const FinniversImageAssetdownload = @"download";
NSString *const FinniversImageAssetearthHourClock = @"earthHourClock";
NSString *const FinniversImageAssetearthHourEarth = @"earthHourEarth";
NSString *const FinniversImageAssetearthHourEyes = @"earthHourEyes";
NSString *const FinniversImageAssetearthHourHeart = @"earthHourHeart";
NSString *const FinniversImageAssetearthHourStars = @"earthHourStars";
NSString *const FinniversImageAsseteasterEgg = @"easterEgg";
NSString *const FinniversImageAssetedit = @"edit";
NSString *const FinniversImageAsseteditBig = @"editBig";
NSString *const FinniversImageAsseterror = @"error";
NSString *const FinniversImageAsseteyeHide = @"eyeHide";
NSString *const FinniversImageAssetfavoriteAdd = @"favoriteAdd";
NSString *const FinniversImageAssetfavouriteAddImg = @"favouriteAddImg";
NSString *const FinniversImageAssetfavouriteAdded = @"favouriteAdded";
NSString *const FinniversImageAssetfavouriteAddedImg = @"favouriteAddedImg";
NSString *const FinniversImageAssetfavourites = @"favourites";
NSString *const FinniversImageAssetfinnLogo = @"finnLogo";
NSString *const FinniversImageAssetgallery = @"gallery";
NSString *const FinniversImageAssetgiftRoundedRectRed = @"giftRoundedRectRed";
NSString *const FinniversImageAssetgiftSquarePink = @"giftSquarePink";
NSString *const FinniversImageAssetgiftSquareYellow = @"giftSquareYellow";
NSString *const FinniversImageAssetgiftTriangleGreen = @"giftTriangleGreen";
NSString *const FinniversImageAssetgridView = @"gridView";
NSString *const FinniversImageAssethelp = @"help";
NSString *const FinniversImageAssethide = @"hide";
NSString *const FinniversImageAssethome = @"home";
NSString *const FinniversImageAsseticonRealestateApartments = @"iconRealestateApartments";
NSString *const FinniversImageAsseticonRealestateBedrooms = @"iconRealestateBedrooms";
NSString *const FinniversImageAsseticonRealestateOwner = @"iconRealestateOwner";
NSString *const FinniversImageAsseticonRealestatePrice = @"iconRealestatePrice";
NSString *const FinniversImageAssetimportant = @"important";
NSString *const FinniversImageAssetinfo = @"info";
NSString *const FinniversImageAssetjobs = @"jobs";
NSString *const FinniversImageAssetlistView = @"listView";
NSString *const FinniversImageAssetmapDirections = @"mapDirections";
NSString *const FinniversImageAssetmapDrawarea = @"mapDrawarea";
NSString *const FinniversImageAssetmapMyposition = @"mapMyposition";
NSString *const FinniversImageAssetmc = @"mc";
NSString *const FinniversImageAssetmessages = @"messages";
NSString *const FinniversImageAssetminus = @"minus";
NSString *const FinniversImageAssetmiscCross = @"miscCross";
NSString *const FinniversImageAssetmiscLike = @"miscLike";
NSString *const FinniversImageAssetmiscLiked = @"miscLiked";
NSString *const FinniversImageAssetmiscMoney = @"miscMoney";
NSString *const FinniversImageAssetmittanbud = @"mittanbud";
NSString *const FinniversImageAssetmore = @"more";
NSString *const FinniversImageAssetmoreImg = @"moreImg";
NSString *const FinniversImageAssetmoteplassen = @"moteplassen";
NSString *const FinniversImageAssetnoImage = @"noImage";
NSString *const FinniversImageAssetnotifications = @"notifications";
NSString *const FinniversImageAssetokonomi = @"okonomi";
NSString *const FinniversImageAssetornamentCircleBlue = @"ornamentCircleBlue";
NSString *const FinniversImageAssetornamentCircleRed = @"ornamentCircleRed";
NSString *const FinniversImageAssetornamentStar = @"ornamentStar";
NSString *const FinniversImageAssetpencilPaper = @"pencilPaper";
NSString *const FinniversImageAssetpin = @"pin";
NSString *const FinniversImageAssetplus = @"plus";
NSString *const FinniversImageAssetprofile = @"profile";
NSString *const FinniversImageAssetrate = @"rate";
NSString *const FinniversImageAssetrated = @"rated";
NSString *const FinniversImageAssetratingCat = @"ratingCat";
NSString *const FinniversImageAssetratingFaceAngry = @"ratingFaceAngry";
NSString *const FinniversImageAssetratingFaceDissatisfied = @"ratingFaceDissatisfied";
NSString *const FinniversImageAssetratingFaceHappy = @"ratingFaceHappy";
NSString *const FinniversImageAssetratingFaceLove = @"ratingFaceLove";
NSString *const FinniversImageAssetratingFaceNeutral = @"ratingFaceNeutral";
NSString *const FinniversImageAssetratings = @"ratings";
NSString *const FinniversImageAssetrealestate = @"realestate";
NSString *const FinniversImageAssetremove = @"remove";
NSString *const FinniversImageAssetrepublish = @"republish";
NSString *const FinniversImageAssetsearch = @"search";
NSString *const FinniversImageAssetsearchBig = @"searchBig";
NSString *const FinniversImageAssetsend = @"send";
NSString *const FinniversImageAssetsettings = @"settings";
NSString *const FinniversImageAssetshare = @"share";
NSString *const FinniversImageAssetshopping = @"shopping";
NSString *const FinniversImageAssetsnowflake = @"snowflake";
NSString *const FinniversImageAssetsold = @"sold";
NSString *const FinniversImageAssetspark = @"spark";
NSString *const FinniversImageAssetspidLogo = @"spidLogo";
NSString *const FinniversImageAssetstatsEmpty = @"statsEmpty";
NSString *const FinniversImageAssetstatsEnvelope = @"statsEnvelope";
NSString *const FinniversImageAssetstatsEye = @"statsEye";
NSString *const FinniversImageAssetstatsHeart = @"statsHeart";
NSString *const FinniversImageAssetsuccess = @"success";
NSString *const FinniversImageAssettrashcan = @"trashcan";
NSString *const FinniversImageAssettravel = @"travel";
NSString *const FinniversImageAssetuncheckCircle = @"uncheckCircle";
NSString *const FinniversImageAssetvehicles = @"vehicles";
NSString *const FinniversImageAssetverified = @"verified";
NSString *const FinniversImageAssetview = @"view";
NSString *const FinniversImageAssetwebview = @"webview";
NSString *const FinniversImageAssetyourads = @"yourads";
@implementation UIImage (FinniversKit)

+ (NSArray<NSString *> *)finniversImageNames {
    return @[
             FinniversImageAssetadManagementShare,
             FinniversImageAssetadManagementTrashcan,
             FinniversImageAssetarrowDown,
             FinniversImageAssetarrowRight,
             FinniversImageAssetarrowUp,
             FinniversImageAssetattachment,
             FinniversImageAssetballoon0,
             FinniversImageAssetballoon1,
             FinniversImageAssetballoon2,
             FinniversImageAssetballoon9,
             FinniversImageAssetblockUser,
             FinniversImageAssetboat,
             FinniversImageAssetcalendar,
             FinniversImageAssetcamera,
             FinniversImageAssetcandyCane,
             FinniversImageAssetcar,
             FinniversImageAssetcheck,
             FinniversImageAssetcheckCircle,
             FinniversImageAssetcheckmarkBig,
             FinniversImageAssetclassifieds,
             FinniversImageAssetclose,
             FinniversImageAssetdistance,
             FinniversImageAssetdownload,
             FinniversImageAssetearthHourClock,
             FinniversImageAssetearthHourEarth,
             FinniversImageAssetearthHourEyes,
             FinniversImageAssetearthHourHeart,
             FinniversImageAssetearthHourStars,
             FinniversImageAsseteasterEgg,
             FinniversImageAssetedit,
             FinniversImageAsseteditBig,
             FinniversImageAsseterror,
             FinniversImageAsseteyeHide,
             FinniversImageAssetfavoriteAdd,
             FinniversImageAssetfavouriteAddImg,
             FinniversImageAssetfavouriteAdded,
             FinniversImageAssetfavouriteAddedImg,
             FinniversImageAssetfavourites,
             FinniversImageAssetfinnLogo,
             FinniversImageAssetgallery,
             FinniversImageAssetgiftRoundedRectRed,
             FinniversImageAssetgiftSquarePink,
             FinniversImageAssetgiftSquareYellow,
             FinniversImageAssetgiftTriangleGreen,
             FinniversImageAssetgridView,
             FinniversImageAssethelp,
             FinniversImageAssethide,
             FinniversImageAssethome,
             FinniversImageAsseticonRealestateApartments,
             FinniversImageAsseticonRealestateBedrooms,
             FinniversImageAsseticonRealestateOwner,
             FinniversImageAsseticonRealestatePrice,
             FinniversImageAssetimportant,
             FinniversImageAssetinfo,
             FinniversImageAssetjobs,
             FinniversImageAssetlistView,
             FinniversImageAssetmapDirections,
             FinniversImageAssetmapDrawarea,
             FinniversImageAssetmapMyposition,
             FinniversImageAssetmc,
             FinniversImageAssetmessages,
             FinniversImageAssetminus,
             FinniversImageAssetmiscCross,
             FinniversImageAssetmiscLike,
             FinniversImageAssetmiscLiked,
             FinniversImageAssetmiscMoney,
             FinniversImageAssetmittanbud,
             FinniversImageAssetmore,
             FinniversImageAssetmoreImg,
             FinniversImageAssetmoteplassen,
             FinniversImageAssetnoImage,
             FinniversImageAssetnotifications,
             FinniversImageAssetokonomi,
             FinniversImageAssetornamentCircleBlue,
             FinniversImageAssetornamentCircleRed,
             FinniversImageAssetornamentStar,
             FinniversImageAssetpencilPaper,
             FinniversImageAssetpin,
             FinniversImageAssetplus,
             FinniversImageAssetprofile,
             FinniversImageAssetrate,
             FinniversImageAssetrated,
             FinniversImageAssetratingCat,
             FinniversImageAssetratingFaceAngry,
             FinniversImageAssetratingFaceDissatisfied,
             FinniversImageAssetratingFaceHappy,
             FinniversImageAssetratingFaceLove,
             FinniversImageAssetratingFaceNeutral,
             FinniversImageAssetratings,
             FinniversImageAssetrealestate,
             FinniversImageAssetremove,
             FinniversImageAssetrepublish,
             FinniversImageAssetsearch,
             FinniversImageAssetsearchBig,
             FinniversImageAssetsend,
             FinniversImageAssetsettings,
             FinniversImageAssetshare,
             FinniversImageAssetshopping,
             FinniversImageAssetsnowflake,
             FinniversImageAssetsold,
             FinniversImageAssetspark,
             FinniversImageAssetspidLogo,
             FinniversImageAssetstatsEmpty,
             FinniversImageAssetstatsEnvelope,
             FinniversImageAssetstatsEye,
             FinniversImageAssetstatsHeart,
             FinniversImageAssetsuccess,
             FinniversImageAssettrashcan,
             FinniversImageAssettravel,
             FinniversImageAssetuncheckCircle,
             FinniversImageAssetvehicles,
             FinniversImageAssetverified,
             FinniversImageAssetview,
             FinniversImageAssetwebview,
             FinniversImageAssetyourads,
             ];
}

@end
