//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

#import "FinniversImageAsset.h"

NSString *const FinniversImageAssetadManagementShare = @"adManagementShare";
NSString *const FinniversImageAssetadManagementTrashcan = @"adManagementTrashcan";
NSString *const FinniversImageAssetarrowDown = @"arrowDown";
NSString *const FinniversImageAssetarrowDownSmall = @"arrowDownSmall";
NSString *const FinniversImageAssetarrowRight = @"arrowRight";
NSString *const FinniversImageAssetarrowUp = @"arrowUp";
NSString *const FinniversImageAssetarrowUpSmall = @"arrowUpSmall";
NSString *const FinniversImageAssetattachment = @"attachment";
NSString *const FinniversImageAssetavatar = @"avatar";
NSString *const FinniversImageAssetballoon0 = @"balloon0";
NSString *const FinniversImageAssetballoon00 = @"balloon00";
NSString *const FinniversImageAssetballoon2 = @"balloon2";
NSString *const FinniversImageAssetballoon22 = @"balloon22";
NSString *const FinniversImageAssetbankID = @"bankID";
NSString *const FinniversImageAssetblockUser = @"blockUser";
NSString *const FinniversImageAssetboat = @"boat";
NSString *const FinniversImageAssetcalendar = @"calendar";
NSString *const FinniversImageAssetcamera = @"camera";
NSString *const FinniversImageAssetcandyCane = @"candyCane";
NSString *const FinniversImageAssetcar = @"car";
NSString *const FinniversImageAssetcheck = @"check";
NSString *const FinniversImageAssetcheckCircle = @"checkCircle";
NSString *const FinniversImageAssetcheckCircleFilledMini = @"checkCircleFilledMini";
NSString *const FinniversImageAssetcheckmarkBig = @"checkmarkBig";
NSString *const FinniversImageAssetchristmasWishListBanner = @"christmasWishListBanner";
NSString *const FinniversImageAssetclassifieds = @"classifieds";
NSString *const FinniversImageAssetclose = @"close";
NSString *const FinniversImageAssetcreditcard = @"creditcard";
NSString *const FinniversImageAssetcross = @"cross";
NSString *const FinniversImageAssetdistance = @"distance";
NSString *const FinniversImageAssetdistanceOutlined = @"distanceOutlined";
NSString *const FinniversImageAssetdocument = @"document";
NSString *const FinniversImageAssetdownload = @"download";
NSString *const FinniversImageAssetearthHourClock = @"earthHourClock";
NSString *const FinniversImageAssetearthHourEarth = @"earthHourEarth";
NSString *const FinniversImageAssetearthHourEyes = @"earthHourEyes";
NSString *const FinniversImageAssetearthHourHeart = @"earthHourHeart";
NSString *const FinniversImageAssetearthHourStars = @"earthHourStars";
NSString *const FinniversImageAsseteasterEgg = @"easterEgg";
NSString *const FinniversImageAssetedit = @"edit";
NSString *const FinniversImageAsseteditBig = @"editBig";
NSString *const FinniversImageAsseterror = @"error";
NSString *const FinniversImageAsseteyeHide = @"eyeHide";
NSString *const FinniversImageAssetfavoriteAdd = @"favoriteAdd";
NSString *const FinniversImageAssetfavoritesComment = @"favoritesComment";
NSString *const FinniversImageAssetfavoritesDelete = @"favoritesDelete";
NSString *const FinniversImageAssetfavoritesEdit = @"favoritesEdit";
NSString *const FinniversImageAssetfavoritesNote = @"favoritesNote";
NSString *const FinniversImageAssetfavoritesPlus = @"favoritesPlus";
NSString *const FinniversImageAssetfavoritesShare = @"favoritesShare";
NSString *const FinniversImageAssetfavoritesShareLink = @"favoritesShareLink";
NSString *const FinniversImageAssetfavoritesSortAdStatus = @"favoritesSortAdStatus";
NSString *const FinniversImageAssetfavoritesSortDistance = @"favoritesSortDistance";
NSString *const FinniversImageAssetfavoritesSortLastAdded = @"favoritesSortLastAdded";
NSString *const FinniversImageAssetfavoritesXmasButton = @"favoritesXmasButton";
NSString *const FinniversImageAssetfavoritesXmasFolder = @"favoritesXmasFolder";
NSString *const FinniversImageAssetfavouriteAddImg = @"favouriteAddImg";
NSString *const FinniversImageAssetfavouriteAdded = @"favouriteAdded";
NSString *const FinniversImageAssetfavouriteAddedImg = @"favouriteAddedImg";
NSString *const FinniversImageAssetfavourites = @"favourites";
NSString *const FinniversImageAssetfinnLogo = @"finnLogo";
NSString *const FinniversImageAssetgallery = @"gallery";
NSString *const FinniversImageAssetgift = @"gift";
NSString *const FinniversImageAssetgiftRoundedRectRed = @"giftRoundedRectRed";
NSString *const FinniversImageAssetgiftSquarePink = @"giftSquarePink";
NSString *const FinniversImageAssetgiftSquareYellow = @"giftSquareYellow";
NSString *const FinniversImageAssetgiftTriangleGreen = @"giftTriangleGreen";
NSString *const FinniversImageAssetgridView = @"gridView";
NSString *const FinniversImageAssethandshake = @"handshake";
NSString *const FinniversImageAssetheartEmpty = @"heartEmpty";
NSString *const FinniversImageAssetheartEmptyDashed = @"heartEmptyDashed";
NSString *const FinniversImageAssethelp = @"help";
NSString *const FinniversImageAssethide = @"hide";
NSString *const FinniversImageAssethome = @"home";
NSString *const FinniversImageAsseticonRealestateApartments = @"iconRealestateApartments";
NSString *const FinniversImageAsseticonRealestateBedrooms = @"iconRealestateBedrooms";
NSString *const FinniversImageAsseticonRealestateOwner = @"iconRealestateOwner";
NSString *const FinniversImageAsseticonRealestatePrice = @"iconRealestatePrice";
NSString *const FinniversImageAssetimportant = @"important";
NSString *const FinniversImageAssetinfo = @"info";
NSString *const FinniversImageAssetjobs = @"jobs";
NSString *const FinniversImageAssetklimaboletBanner = @"klimaboletBanner";
NSString *const FinniversImageAssetlistView = @"listView";
NSString *const FinniversImageAssetmagnifyingGlass = @"magnifyingGlass";
NSString *const FinniversImageAssetmapDirections = @"mapDirections";
NSString *const FinniversImageAssetmapDrawarea = @"mapDrawarea";
NSString *const FinniversImageAssetmapMyposition = @"mapMyposition";
NSString *const FinniversImageAssetmc = @"mc";
NSString *const FinniversImageAssetmessages = @"messages";
NSString *const FinniversImageAssetminus = @"minus";
NSString *const FinniversImageAssetminusCircleFilledMini = @"minusCircleFilledMini";
NSString *const FinniversImageAssetmiscCross = @"miscCross";
NSString *const FinniversImageAssetmiscLike = @"miscLike";
NSString *const FinniversImageAssetmiscLiked = @"miscLiked";
NSString *const FinniversImageAssetmiscMoney = @"miscMoney";
NSString *const FinniversImageAssetmittanbud = @"mittanbud";
NSString *const FinniversImageAssetmore = @"more";
NSString *const FinniversImageAssetmoreImg = @"moreImg";
NSString *const FinniversImageAssetmoteplassen = @"moteplassen";
NSString *const FinniversImageAssetnavigation = @"navigation";
NSString *const FinniversImageAssetnoImage = @"noImage";
NSString *const FinniversImageAssetnotifications = @"notifications";
NSString *const FinniversImageAssetokonomi = @"okonomi";
NSString *const FinniversImageAssetornamentCircleBlue = @"ornamentCircleBlue";
NSString *const FinniversImageAssetornamentCircleRed = @"ornamentCircleRed";
NSString *const FinniversImageAssetornamentStar = @"ornamentStar";
NSString *const FinniversImageAssetpencilPaper = @"pencilPaper";
NSString *const FinniversImageAssetpin = @"pin";
NSString *const FinniversImageAssetplus = @"plus";
NSString *const FinniversImageAssetplusMini = @"plusMini";
NSString *const FinniversImageAssetprimingFavoritesComments = @"primingFavoritesComments";
NSString *const FinniversImageAssetprimingFavoritesSearch = @"primingFavoritesSearch";
NSString *const FinniversImageAssetprimingFavoritesSharing = @"primingFavoritesSharing";
NSString *const FinniversImageAssetprofile = @"profile";
NSString *const FinniversImageAssetrate = @"rate";
NSString *const FinniversImageAssetrated = @"rated";
NSString *const FinniversImageAssetratingCat = @"ratingCat";
NSString *const FinniversImageAssetratingFaceAngry = @"ratingFaceAngry";
NSString *const FinniversImageAssetratingFaceDissatisfied = @"ratingFaceDissatisfied";
NSString *const FinniversImageAssetratingFaceHappy = @"ratingFaceHappy";
NSString *const FinniversImageAssetratingFaceLove = @"ratingFaceLove";
NSString *const FinniversImageAssetratingFaceNeutral = @"ratingFaceNeutral";
NSString *const FinniversImageAssetratings = @"ratings";
NSString *const FinniversImageAssetrealestate = @"realestate";
NSString *const FinniversImageAssetremove = @"remove";
NSString *const FinniversImageAssetrepublish = @"republish";
NSString *const FinniversImageAssetsearch = @"search";
NSString *const FinniversImageAssetsearchBig = @"searchBig";
NSString *const FinniversImageAssetsend = @"send";
NSString *const FinniversImageAssetsettings = @"settings";
NSString *const FinniversImageAssetshare = @"share";
NSString *const FinniversImageAssetshopping = @"shopping";
NSString *const FinniversImageAssetsliderThumb = @"sliderThumb";
NSString *const FinniversImageAssetsliderThumbActive = @"sliderThumbActive";
NSString *const FinniversImageAssetsnowflake = @"snowflake";
NSString *const FinniversImageAssetsold = @"sold";
NSString *const FinniversImageAssetspark = @"spark";
NSString *const FinniversImageAssetspeechbubbleSmiley = @"speechbubbleSmiley";
NSString *const FinniversImageAssetspidLogo = @"spidLogo";
NSString *const FinniversImageAssetsplashLetters1 = @"splashLetters1";
NSString *const FinniversImageAssetsplashLetters2 = @"splashLetters2";
NSString *const FinniversImageAssetsplashLetters3 = @"splashLetters3";
NSString *const FinniversImageAssetsplashLetters4 = @"splashLetters4";
NSString *const FinniversImageAssetsplashLogo = @"splashLogo";
NSString *const FinniversImageAssetstarOutline = @"starOutline";
NSString *const FinniversImageAssetstatsEmpty = @"statsEmpty";
NSString *const FinniversImageAssetstatsEnvelope = @"statsEnvelope";
NSString *const FinniversImageAssetstatsEye = @"statsEye";
NSString *const FinniversImageAssetstatsHeart = @"statsHeart";
NSString *const FinniversImageAssetsuccess = @"success";
NSString *const FinniversImageAssettrashcan = @"trashcan";
NSString *const FinniversImageAssettravel = @"travel";
NSString *const FinniversImageAssetuncheckCircle = @"uncheckCircle";
NSString *const FinniversImageAssetvehicles = @"vehicles";
NSString *const FinniversImageAssetverified = @"verified";
NSString *const FinniversImageAssetview = @"view";
NSString *const FinniversImageAssetwebview = @"webview";
NSString *const FinniversImageAssetwrench = @"wrench";
NSString *const FinniversImageAssetyourads = @"yourads";
@implementation UIImage (FinniversKit)

+ (NSArray<NSString *> *)finniversImageNames {
    return @[
             FinniversImageAssetadManagementShare,
             FinniversImageAssetadManagementTrashcan,
             FinniversImageAssetarrowDown,
             FinniversImageAssetarrowDownSmall,
             FinniversImageAssetarrowRight,
             FinniversImageAssetarrowUp,
             FinniversImageAssetarrowUpSmall,
             FinniversImageAssetattachment,
             FinniversImageAssetavatar,
             FinniversImageAssetballoon0,
             FinniversImageAssetballoon00,
             FinniversImageAssetballoon2,
             FinniversImageAssetballoon22,
             FinniversImageAssetbankID,
             FinniversImageAssetblockUser,
             FinniversImageAssetboat,
             FinniversImageAssetcalendar,
             FinniversImageAssetcamera,
             FinniversImageAssetcandyCane,
             FinniversImageAssetcar,
             FinniversImageAssetcheck,
             FinniversImageAssetcheckCircle,
             FinniversImageAssetcheckCircleFilledMini,
             FinniversImageAssetcheckmarkBig,
             FinniversImageAssetchristmasWishListBanner,
             FinniversImageAssetclassifieds,
             FinniversImageAssetclose,
             FinniversImageAssetcreditcard,
             FinniversImageAssetcross,
             FinniversImageAssetdistance,
             FinniversImageAssetdistanceOutlined,
             FinniversImageAssetdocument,
             FinniversImageAssetdownload,
             FinniversImageAssetearthHourClock,
             FinniversImageAssetearthHourEarth,
             FinniversImageAssetearthHourEyes,
             FinniversImageAssetearthHourHeart,
             FinniversImageAssetearthHourStars,
             FinniversImageAsseteasterEgg,
             FinniversImageAssetedit,
             FinniversImageAsseteditBig,
             FinniversImageAsseterror,
             FinniversImageAsseteyeHide,
             FinniversImageAssetfavoriteAdd,
             FinniversImageAssetfavoritesComment,
             FinniversImageAssetfavoritesDelete,
             FinniversImageAssetfavoritesEdit,
             FinniversImageAssetfavoritesNote,
             FinniversImageAssetfavoritesPlus,
             FinniversImageAssetfavoritesShare,
             FinniversImageAssetfavoritesShareLink,
             FinniversImageAssetfavoritesSortAdStatus,
             FinniversImageAssetfavoritesSortDistance,
             FinniversImageAssetfavoritesSortLastAdded,
             FinniversImageAssetfavoritesXmasButton,
             FinniversImageAssetfavoritesXmasFolder,
             FinniversImageAssetfavouriteAddImg,
             FinniversImageAssetfavouriteAdded,
             FinniversImageAssetfavouriteAddedImg,
             FinniversImageAssetfavourites,
             FinniversImageAssetfinnLogo,
             FinniversImageAssetgallery,
             FinniversImageAssetgift,
             FinniversImageAssetgiftRoundedRectRed,
             FinniversImageAssetgiftSquarePink,
             FinniversImageAssetgiftSquareYellow,
             FinniversImageAssetgiftTriangleGreen,
             FinniversImageAssetgridView,
             FinniversImageAssethandshake,
             FinniversImageAssetheartEmpty,
             FinniversImageAssetheartEmptyDashed,
             FinniversImageAssethelp,
             FinniversImageAssethide,
             FinniversImageAssethome,
             FinniversImageAsseticonRealestateApartments,
             FinniversImageAsseticonRealestateBedrooms,
             FinniversImageAsseticonRealestateOwner,
             FinniversImageAsseticonRealestatePrice,
             FinniversImageAssetimportant,
             FinniversImageAssetinfo,
             FinniversImageAssetjobs,
             FinniversImageAssetklimaboletBanner,
             FinniversImageAssetlistView,
             FinniversImageAssetmagnifyingGlass,
             FinniversImageAssetmapDirections,
             FinniversImageAssetmapDrawarea,
             FinniversImageAssetmapMyposition,
             FinniversImageAssetmc,
             FinniversImageAssetmessages,
             FinniversImageAssetminus,
             FinniversImageAssetminusCircleFilledMini,
             FinniversImageAssetmiscCross,
             FinniversImageAssetmiscLike,
             FinniversImageAssetmiscLiked,
             FinniversImageAssetmiscMoney,
             FinniversImageAssetmittanbud,
             FinniversImageAssetmore,
             FinniversImageAssetmoreImg,
             FinniversImageAssetmoteplassen,
             FinniversImageAssetnavigation,
             FinniversImageAssetnoImage,
             FinniversImageAssetnotifications,
             FinniversImageAssetokonomi,
             FinniversImageAssetornamentCircleBlue,
             FinniversImageAssetornamentCircleRed,
             FinniversImageAssetornamentStar,
             FinniversImageAssetpencilPaper,
             FinniversImageAssetpin,
             FinniversImageAssetplus,
             FinniversImageAssetplusMini,
             FinniversImageAssetprimingFavoritesComments,
             FinniversImageAssetprimingFavoritesSearch,
             FinniversImageAssetprimingFavoritesSharing,
             FinniversImageAssetprofile,
             FinniversImageAssetrate,
             FinniversImageAssetrated,
             FinniversImageAssetratingCat,
             FinniversImageAssetratingFaceAngry,
             FinniversImageAssetratingFaceDissatisfied,
             FinniversImageAssetratingFaceHappy,
             FinniversImageAssetratingFaceLove,
             FinniversImageAssetratingFaceNeutral,
             FinniversImageAssetratings,
             FinniversImageAssetrealestate,
             FinniversImageAssetremove,
             FinniversImageAssetrepublish,
             FinniversImageAssetsearch,
             FinniversImageAssetsearchBig,
             FinniversImageAssetsend,
             FinniversImageAssetsettings,
             FinniversImageAssetshare,
             FinniversImageAssetshopping,
             FinniversImageAssetsliderThumb,
             FinniversImageAssetsliderThumbActive,
             FinniversImageAssetsnowflake,
             FinniversImageAssetsold,
             FinniversImageAssetspark,
             FinniversImageAssetspeechbubbleSmiley,
             FinniversImageAssetspidLogo,
             FinniversImageAssetsplashLetters1,
             FinniversImageAssetsplashLetters2,
             FinniversImageAssetsplashLetters3,
             FinniversImageAssetsplashLetters4,
             FinniversImageAssetsplashLogo,
             FinniversImageAssetstarOutline,
             FinniversImageAssetstatsEmpty,
             FinniversImageAssetstatsEnvelope,
             FinniversImageAssetstatsEye,
             FinniversImageAssetstatsHeart,
             FinniversImageAssetsuccess,
             FinniversImageAssettrashcan,
             FinniversImageAssettravel,
             FinniversImageAssetuncheckCircle,
             FinniversImageAssetvehicles,
             FinniversImageAssetverified,
             FinniversImageAssetview,
             FinniversImageAssetwebview,
             FinniversImageAssetwrench,
             FinniversImageAssetyourads,
             ];
}

@end
