//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

@import UIKit;

extern NSString *const FinniversImageAssetarrowDown;
extern NSString *const FinniversImageAssetarrowRight;
extern NSString *const FinniversImageAssetarrowUp;
extern NSString *const FinniversImageAssetattachment;
extern NSString *const FinniversImageAssetblockUser;
extern NSString *const FinniversImageAssetboat;
extern NSString *const FinniversImageAssetcalendar;
extern NSString *const FinniversImageAssetcamera;
extern NSString *const FinniversImageAssetcar;
extern NSString *const FinniversImageAssetcheck;
extern NSString *const FinniversImageAssetcheckmarkBig;
extern NSString *const FinniversImageAssetclassifieds;
extern NSString *const FinniversImageAssetdistance;
extern NSString *const FinniversImageAssetdownload;
extern NSString *const FinniversImageAsseteasterEgg;
extern NSString *const FinniversImageAssetedit;
extern NSString *const FinniversImageAsseteditBig;
extern NSString *const FinniversImageAsseterror;
extern NSString *const FinniversImageAssetfavouriteAdd;
extern NSString *const FinniversImageAssetfavouriteAddImg;
extern NSString *const FinniversImageAssetfavouriteAdded;
extern NSString *const FinniversImageAssetfavouriteAddedImg;
extern NSString *const FinniversImageAssetfavourites;
extern NSString *const FinniversImageAssetgallery;
extern NSString *const FinniversImageAssetgridView;
extern NSString *const FinniversImageAssethelp;
extern NSString *const FinniversImageAssethide;
extern NSString *const FinniversImageAssethome;
extern NSString *const FinniversImageAssetimportant;
extern NSString *const FinniversImageAssetinfo;
extern NSString *const FinniversImageAssetjobs;
extern NSString *const FinniversImageAssetlistView;
extern NSString *const FinniversImageAssetmapDirections;
extern NSString *const FinniversImageAssetmapDrawarea;
extern NSString *const FinniversImageAssetmapMyposition;
extern NSString *const FinniversImageAssetmc;
extern NSString *const FinniversImageAssetmessages;
extern NSString *const FinniversImageAssetminus;
extern NSString *const FinniversImageAssetmiscLike;
extern NSString *const FinniversImageAssetmiscLiked;
extern NSString *const FinniversImageAssetmiscMoney;
extern NSString *const FinniversImageAssetmittanbud;
extern NSString *const FinniversImageAssetmore;
extern NSString *const FinniversImageAssetmoreImg;
extern NSString *const FinniversImageAssetmoteplassen;
extern NSString *const FinniversImageAssetnoImage;
extern NSString *const FinniversImageAssetnotifications;
extern NSString *const FinniversImageAssetonlyNew;
extern NSString *const FinniversImageAssetpin;
extern NSString *const FinniversImageAssetplus;
extern NSString *const FinniversImageAssetprofile;
extern NSString *const FinniversImageAssetrate;
extern NSString *const FinniversImageAssetrated;
extern NSString *const FinniversImageAssetratings;
extern NSString *const FinniversImageAssetrealestate;
extern NSString *const FinniversImageAssetremove;
extern NSString *const FinniversImageAssetsearch;
extern NSString *const FinniversImageAssetsearchBig;
extern NSString *const FinniversImageAssetsend;
extern NSString *const FinniversImageAssetsettings;
extern NSString *const FinniversImageAssetshare;
extern NSString *const FinniversImageAssetshopping;
extern NSString *const FinniversImageAssetsmalljobs;
extern NSString *const FinniversImageAssetspidLogo;
extern NSString *const FinniversImageAssetsuccess;
extern NSString *const FinniversImageAssettrashcan;
extern NSString *const FinniversImageAssettravel;
extern NSString *const FinniversImageAssetvehicles;
extern NSString *const FinniversImageAssetverified;
extern NSString *const FinniversImageAssetview;
extern NSString *const FinniversImageAssetwebview;
extern NSString *const FinniversImageAssetyourads;


@interface UIImage (FinniversKit)
+ (NSArray<NSString *> *)finniversImageNames;
@end
