//
//  Copyright © FINN.no AS, Inc. All rights reserved.
//

// Generated by generate_image_assets_symbols as a "Run Script" Build Phase
// WARNING: This file is autogenerated, do not modify by hand

import UIKit

public extension UIImage {
    public convenience init(named imageAsset: FinniversImageAsset) {
        self.init(named: imageAsset.rawValue, in: FinniversKit.bundle, compatibleWith: nil)!
    }

    @objc public class func assetNamed(_ assetName: String) -> UIImage {
        return UIImage(named: assetName, in: FinniversKit.bundle, compatibleWith: nil)!
    }
}

public enum FinniversImageAsset: String {
    case adManagementShare
    case adManagementTrashcan
    case arrowDown
    case arrowRight
    case arrowUp
    case attachment
    case balloon0
    case balloon1
    case balloon2
    case balloon9
    case blockUser
    case boat
    case calendar
    case camera
    case candyCane
    case car
    case check
    case checkCircle
    case checkmarkBig
    case classifieds
    case close
    case distance
    case download
    case earthHourClock
    case earthHourEarth
    case earthHourEyes
    case earthHourHeart
    case earthHourStars
    case easterEgg
    case edit
    case editBig
    case error
    case eyeHide
    case favoriteAdd
    case favouriteAddImg
    case favouriteAdded
    case favouriteAddedImg
    case favourites
    case finnLogo
    case gallery
    case giftRoundedRectRed
    case giftSquarePink
    case giftSquareYellow
    case giftTriangleGreen
    case gridView
    case help
    case hide
    case home
    case important
    case info
    case jobs
    case listView
    case mapDirections
    case mapDrawarea
    case mapMyposition
    case mc
    case messages
    case minus
    case miscCross
    case miscLike
    case miscLiked
    case miscMoney
    case mittanbud
    case more
    case moreImg
    case moteplassen
    case noImage
    case notifications
    case ornamentCircleBlue
    case ornamentCircleRed
    case ornamentStar
    case pencilPaper
    case pin
    case plus
    case profile
    case rate
    case rated
    case ratingCat
    case ratingFaceAngry
    case ratingFaceDissatisfied
    case ratingFaceHappy
    case ratingFaceLove
    case ratingFaceNeutral
    case ratings
    case realestate
    case remove
    case republish
    case search
    case searchBig
    case send
    case settings
    case share
    case shopping
    case smalljobs
    case snowflake
    case sold
    case spark
    case spidLogo
    case statsEmpty
    case statsEnvelope
    case statsEye
    case statsHeart
    case success
    case trashcan
    case travel
    case vehicles
    case verified
    case view
    case webview
    case yourads

    public static var imageNames: [FinniversImageAsset] {
        return [
            .adManagementShare,
            .adManagementTrashcan,
            .arrowDown,
            .arrowRight,
            .arrowUp,
            .attachment,
            .balloon0,
            .balloon1,
            .balloon2,
            .balloon9,
            .blockUser,
            .boat,
            .calendar,
            .camera,
            .candyCane,
            .car,
            .check,
            .checkCircle,
            .checkmarkBig,
            .classifieds,
            .close,
            .distance,
            .download,
            .earthHourClock,
            .earthHourEarth,
            .earthHourEyes,
            .earthHourHeart,
            .earthHourStars,
            .easterEgg,
            .edit,
            .editBig,
            .error,
            .eyeHide,
            .favoriteAdd,
            .favouriteAddImg,
            .favouriteAdded,
            .favouriteAddedImg,
            .favourites,
            .finnLogo,
            .gallery,
            .giftRoundedRectRed,
            .giftSquarePink,
            .giftSquareYellow,
            .giftTriangleGreen,
            .gridView,
            .help,
            .hide,
            .home,
            .important,
            .info,
            .jobs,
            .listView,
            .mapDirections,
            .mapDrawarea,
            .mapMyposition,
            .mc,
            .messages,
            .minus,
            .miscCross,
            .miscLike,
            .miscLiked,
            .miscMoney,
            .mittanbud,
            .more,
            .moreImg,
            .moteplassen,
            .noImage,
            .notifications,
            .ornamentCircleBlue,
            .ornamentCircleRed,
            .ornamentStar,
            .pencilPaper,
            .pin,
            .plus,
            .profile,
            .rate,
            .rated,
            .ratingCat,
            .ratingFaceAngry,
            .ratingFaceDissatisfied,
            .ratingFaceHappy,
            .ratingFaceLove,
            .ratingFaceNeutral,
            .ratings,
            .realestate,
            .remove,
            .republish,
            .search,
            .searchBig,
            .send,
            .settings,
            .share,
            .shopping,
            .smalljobs,
            .snowflake,
            .sold,
            .spark,
            .spidLogo,
            .statsEmpty,
            .statsEnvelope,
            .statsEye,
            .statsHeart,
            .success,
            .trashcan,
            .travel,
            .vehicles,
            .verified,
            .view,
            .webview,
            .yourads,
    ]
  }
}
