name: iOS build and test

on:
  push:
    branches: [ "master", "test_ga_build" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-14
    env:
      scheme: ${{ 'Demo' }}
      destination: ${{ 'platform=iOS Simulator,OS=15.2,name=iPhone 13 Pro' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Lint
        run: |
          swiftlint lint
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -workspace FinniversKit.xcworkspace -destination "$destination"
      - name: Test        
        run: |
          xcodebuild test-without-building -scheme "$scheme" -workspace FinniversKit.xcworkspace -destination "$destination"
